"""Train and export the independent embedded-model v2 project.

Run from the PDM_V1 root:
    python embedded_model_v2/train_export_v2.py
"""
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, balanced_accuracy_score, classification_report, f1_score
from sklearn.model_selection import StratifiedGroupKFold


ROOT = Path(__file__).resolve().parent
DATASET = ROOT.parent / "log_file/output290826/ml_dataset.csv"
ARTIFACTS = ROOT / "model_artifacts"
HEADER = ROOT / "include/motor_model_v2.h"

FEATURES = [
    "az_mean", "rpm_min", "ay_rms", "ay_std", "ax_crest", "rpm_median",
    "rpm_max", "ay_p2p", "ax_rms", "ax_std", "acs_rms", "acs_mean",
]
LABELS = ["F1", "F2", "F3", "F4", "HEALTHY"]
MODEL_ARGS = dict(
    n_estimators=25,
    max_depth=5,
    min_samples_leaf=3,
    max_features="sqrt",
    class_weight="balanced_subsample",
    random_state=42,
    n_jobs=-1,
)


def emit_node(tree, node, indent, tree_index):
    left, right = tree.children_left[node], tree.children_right[node]
    if left == right:
        values = tree.value[node][0]
        total = float(np.sum(values))
        additions = " ".join(
            f"votes[{index}] += {c_float(value / total)};"
            for index, value in enumerate(values) if value > 0
        )
        return [f"{indent}{additions}", f"{indent}return;"]
    feature, threshold = int(tree.feature[node]), float(tree.threshold[node])
    lines = [f"{indent}if (features[{feature}] <= {c_float(threshold)}) {{"]
    lines.extend(emit_node(tree, left, indent + "  ", tree_index))
    lines.append(f"{indent}}} else {{")
    lines.extend(emit_node(tree, right, indent + "  ", tree_index))
    lines.append(f"{indent}}}")
    return lines


def c_float(value):
    """Return a valid C++ single-precision literal, including for 1.0."""
    text = f"{float(value):.9g}"
    if "." not in text and "e" not in text.lower():
        text += ".0"
    return text + "f"


def export_header(model):
    tree_functions = []
    calls = []
    for index, estimator in enumerate(model.estimators_):
        tree_functions += [f"inline void motorV2Tree{index}(const float features[], float votes[]) {{"]
        tree_functions += emit_node(estimator.tree_, 0, "  ", index)
        tree_functions += ["}", ""]
        calls.append(f"  motorV2Tree{index}(features, votes);")

    feature_names = ", ".join(f'"{name}"' for name in FEATURES)
    label_names = ", ".join(f'"{name}"' for name in model.classes_)
    source = f"""// Generated by train_export_v2.py. Do not edit manually.
#pragma once

constexpr int MOTOR_V2_FEATURE_COUNT = {len(FEATURES)};
constexpr int MOTOR_V2_CLASS_COUNT = {len(model.classes_)};
static const char *const MOTOR_V2_FEATURE_NAMES[] = {{{feature_names}}};
static const char *const MOTOR_V2_LABELS[] = {{{label_names}}};

{chr(10).join(tree_functions)}
inline int motorV2Predict(const float features[MOTOR_V2_FEATURE_COUNT], float *confidence) {{
  float votes[MOTOR_V2_CLASS_COUNT] = {{0}};
{chr(10).join(calls)}
  int best = 0;
  for (int i = 1; i < MOTOR_V2_CLASS_COUNT; ++i) if (votes[i] > votes[best]) best = i;
  if (confidence != nullptr) *confidence = votes[best] / {len(model.estimators_)}.0f;
  return best;
}}
"""
    HEADER.write_text(source)


def main():
    ARTIFACTS.mkdir(exist_ok=True)
    df = pd.read_csv(DATASET)
    x, y, groups = df[FEATURES], df["fault_id"], df["group"]
    cv = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
    actual, predicted = [], []
    for train, test in cv.split(x, y, groups):
        model = RandomForestClassifier(**MODEL_ARGS).fit(x.iloc[train], y.iloc[train])
        actual.extend(y.iloc[test])
        predicted.extend(model.predict(x.iloc[test]))

    report = (
        "Embedded Model V2: 25-tree Random Forest (max depth 5)\n"
        f"Accuracy: {accuracy_score(actual, predicted) * 100:.2f}%\n"
        f"Balanced accuracy: {balanced_accuracy_score(actual, predicted) * 100:.2f}%\n"
        f"Macro F1: {f1_score(actual, predicted, average='macro'):.3f}\n\n"
        + classification_report(actual, predicted, labels=LABELS, zero_division=0)
    )
    print(report)
    (ARTIFACTS / "validation_report.txt").write_text(report)

    final_model = RandomForestClassifier(**MODEL_ARGS).fit(x, y)
    joblib.dump({"model": final_model, "features": FEATURES, "labels": LABELS}, ARTIFACTS / "motor_rf_v2.pkl")
    export_header(final_model)
    print(f"Exported {HEADER}")


if __name__ == "__main__":
    main()
