// Generated by log_file/scripts/train_embedded_model.py. Do not edit manually.
#pragma once

constexpr int MOTOR_FEATURE_COUNT = 8;
static const char *const MOTOR_FEATURE_NAMES[MOTOR_FEATURE_COUNT] = {"az_mean", "rpm_min", "ay_rms", "ay_std", "ax_crest", "rpm_median", "rpm_max", "ay_p2p"};
static const char *const MOTOR_LABELS[] = {"F1", "F2", "F3", "F4", "HEALTHY"};

// Feature order: az_mean, rpm_min, ay_rms, ay_std, ax_crest, rpm_median, rpm_max, ay_p2p.
// Return value is the index into MOTOR_LABELS.
inline int motorPredict(const float features[MOTOR_FEATURE_COUNT]) {
  if (features[0] <= 10.8436751f) {
    if (features[1] <= 2785.58008f) {
      if (features[6] <= 2642.22498f) {
        if (features[0] <= 10.8284373f) {
          return 4;
        } else {
          return 3;
        }
      } else {
        if (features[3] <= 1.53467399f) {
          return 3;
        } else {
          if (features[7] <= 6.80429983f) {
            return 2;
          } else {
            if (features[4] <= 2.04381633f) {
              return 3;
            } else {
              return 3;
            }
          }
        }
      }
    } else {
      if (features[7] <= 5.20500016f) {
        if (features[1] <= 2901.59497f) {
          return 4;
        } else {
          if (features[6] <= 3002.02502f) {
            if (features[4] <= 1.50256622f) {
              return 2;
            } else {
              return 2;
            }
          } else {
            if (features[4] <= 1.51759934f) {
              return 4;
            } else {
              return 4;
            }
          }
        }
      } else {
        if (features[4] <= 1.38179165f) {
          return 2;
        } else {
          return 4;
        }
      }
    }
  } else {
    if (features[0] <= 10.8731356f) {
      if (features[6] <= 2949.3501f) {
        if (features[5] <= 2795.70508f) {
          return 2;
        } else {
          if (features[2] <= 1.68747532f) {
            return 0;
          } else {
            return 0;
          }
        }
      } else {
        if (features[6] <= 2964.80994f) {
          return 1;
        } else {
          if (features[6] <= 3003.97998f) {
            if (features[3] <= 1.77180755f) {
              return 2;
            } else {
              return 2;
            }
          } else {
            return 3;
          }
        }
      }
    } else {
      if (features[6] <= 2962.38f) {
        if (features[7] <= 5.52939987f) {
          if (features[0] <= 10.8750496f) {
            return 1;
          } else {
            return 1;
          }
        } else {
          return 1;
        }
      } else {
        if (features[1] <= 2644.14001f) {
          return 3;
        } else {
          if (features[3] <= 1.7445839f) {
            return 2;
          } else {
            return 2;
          }
        }
      }
    }
  }
}
