// Generated by train_export_v2.py. Do not edit manually.
#pragma once

constexpr int MOTOR_V2_FEATURE_COUNT = 12;
constexpr int MOTOR_V2_CLASS_COUNT = 5;
static const char *const MOTOR_V2_FEATURE_NAMES[] = {"az_mean", "rpm_min", "ay_rms", "ay_std", "ax_crest", "rpm_median", "rpm_max", "ay_p2p", "ax_rms", "ax_std", "acs_rms", "acs_mean"};
static const char *const MOTOR_V2_LABELS[] = {"F1", "F2", "F3", "F4", "HEALTHY"};

inline void motorV2Tree0(const float features[], float votes[]) {
  if (features[9] <= 3.41028619f) {
    if (features[4] <= 1.41210729f) {
      if (features[2] <= 1.69585264f) {
        if (features[6] <= 2771.70496f) {
          votes[1] += 1.0f;
          return;
        } else {
          if (features[0] <= 10.8459129f) {
            votes[0] += 0.731922399f; votes[3] += 0.268077601f;
            return;
          } else {
            votes[0] += 1.0f;
            return;
          }
        }
      } else {
        if (features[6] <= 2980.38501f) {
          if (features[6] <= 2941.755f) {
            votes[1] += 1.0f;
            return;
          } else {
            votes[1] += 1.0f;
            return;
          }
        } else {
          votes[3] += 0.865565274f; votes[4] += 0.134434726f;
          return;
        }
      }
    } else {
      if (features[2] <= 1.53467399f) {
        votes[3] += 1.0f;
        return;
      } else {
        if (features[1] <= 2787.91003f) {
          if (features[7] <= 7.01259971f) {
            votes[0] += 0.0800906924f; votes[1] += 0.349247937f; votes[2] += 0.324634273f; votes[4] += 0.246027097f;
            return;
          } else {
            votes[3] += 0.995875366f; votes[4] += 0.0041246335f;
            return;
          }
        } else {
          if (features[3] <= 1.67991513f) {
            votes[0] += 0.621027721f; votes[4] += 0.378972279f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    }
  } else {
    if (features[11] <= 1364.31f) {
      if (features[5] <= 3000.86243f) {
        votes[2] += 1.0f;
        return;
      } else {
        votes[4] += 1.0f;
        return;
      }
    } else {
      votes[4] += 1.0f;
      return;
    }
  }
}

inline void motorV2Tree1(const float features[], float votes[]) {
  if (features[5] <= 2980.10999f) {
    if (features[2] <= 1.5612185f) {
      if (features[10] <= 1473.72418f) {
        votes[3] += 1.0f;
        return;
      } else {
        votes[4] += 1.0f;
        return;
      }
    } else {
      if (features[6] <= 2940.52502f) {
        if (features[3] <= 1.69219768f) {
          if (features[6] <= 2794.40503f) {
            votes[1] += 0.663184719f; votes[2] += 0.133626772f; votes[4] += 0.20318851f;
            return;
          } else {
            votes[0] += 0.923135553f; votes[4] += 0.0768644465f;
            return;
          }
        } else {
          if (features[9] <= 3.02261627f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[1] += 0.969072165f; votes[4] += 0.0309278351f;
            return;
          }
        }
      } else {
        if (features[2] <= 1.74280697f) {
          if (features[7] <= 5.21340013f) {
            votes[0] += 0.459419634f; votes[2] += 0.473133653f; votes[4] += 0.0674467123f;
            return;
          } else {
            votes[1] += 1.0f;
            return;
          }
        } else {
          if (features[1] <= 2827.97498f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    }
  } else {
    if (features[7] <= 5.21700001f) {
      if (features[1] <= 3000.15002f) {
        if (features[6] <= 3002.02502f) {
          if (features[10] <= 1370.2019f) {
            votes[2] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        } else {
          votes[2] += 0.875232775f; votes[4] += 0.124767225f;
          return;
        }
      } else {
        votes[4] += 1.0f;
        return;
      }
    } else {
      if (features[3] <= 2.05093598f) {
        if (features[0] <= 10.8540115f) {
          votes[4] += 1.0f;
          return;
        } else {
          votes[3] += 0.820721769f; votes[4] += 0.179278231f;
          return;
        }
      } else {
        votes[2] += 0.738879714f; votes[3] += 0.214307103f; votes[4] += 0.0468131828f;
        return;
      }
    }
  }
}

inline void motorV2Tree2(const float features[], float votes[]) {
  if (features[2] <= 1.56134349f) {
    if (features[8] <= 1.11859733f) {
      if (features[2] <= 1.48045719f) {
        votes[3] += 1.0f;
        return;
      } else {
        votes[4] += 1.0f;
        return;
      }
    } else {
      if (features[7] <= 4.7033999f) {
        votes[3] += 1.0f;
        return;
      } else {
        votes[3] += 1.0f;
        return;
      }
    }
  } else {
    if (features[1] <= 2980.69995f) {
      if (features[10] <= 1440.17859f) {
        if (features[2] <= 1.69038045f) {
          if (features[9] <= 2.22832012f) {
            votes[1] += 0.724205062f; votes[2] += 0.275794938f;
            return;
          } else {
            votes[0] += 0.919079177f; votes[1] += 0.0216253924f; votes[2] += 0.0592954308f;
            return;
          }
        } else {
          if (features[9] <= 2.83748233f) {
            votes[3] += 0.537873523f; votes[4] += 0.462126477f;
            return;
          } else {
            votes[1] += 0.961748261f; votes[2] += 0.020285013f; votes[3] += 0.0179667258f;
            return;
          }
        }
      } else {
        votes[4] += 1.0f;
        return;
      }
    } else {
      if (features[1] <= 3000.15002f) {
        if (features[11] <= 1368.20752f) {
          if (features[10] <= 1324.5025f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[2] += 1.0f;
            return;
          }
        } else {
          if (features[0] <= 10.8155699f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      } else {
        votes[4] += 1.0f;
        return;
      }
    }
  }
}

inline void motorV2Tree3(const float features[], float votes[]) {
  if (features[5] <= 2981.14502f) {
    if (features[5] <= 2938.51501f) {
      if (features[6] <= 3036.06006f) {
        if (features[0] <= 10.8427744f) {
          if (features[1] <= 2786.09998f) {
            votes[1] += 0.0568104351f; votes[2] += 0.0852156526f; votes[3] += 0.716139234f; votes[4] += 0.141834678f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        } else {
          if (features[5] <= 2769.52747f) {
            votes[1] += 0.785714286f; votes[2] += 0.214285714f;
            return;
          } else {
            votes[0] += 0.99330656f; votes[4] += 0.00669344043f;
            return;
          }
        }
      } else {
        if (features[1] <= 2827.97498f) {
          if (features[11] <= 1406.21252f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[3] += 0.934508816f; votes[4] += 0.0654911839f;
            return;
          }
        } else {
          votes[4] += 1.0f;
          return;
        }
      }
    } else {
      if (features[9] <= 3.02717149f) {
        votes[4] += 1.0f;
        return;
      } else {
        if (features[0] <= 10.8507462f) {
          votes[4] += 1.0f;
          return;
        } else {
          votes[1] += 1.0f;
          return;
        }
      }
    }
  } else {
    if (features[6] <= 3002.55005f) {
      if (features[10] <= 1370.18939f) {
        if (features[6] <= 2984.10999f) {
          if (features[10] <= 1267.54498f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[2] += 0.975032852f; votes[4] += 0.0249671485f;
            return;
          }
        } else {
          if (features[4] <= 1.54628915f) {
            votes[2] += 1.0f;
            return;
          } else {
            votes[2] += 0.928660826f; votes[4] += 0.071339174f;
            return;
          }
        }
      } else {
        votes[4] += 1.0f;
        return;
      }
    } else {
      if (features[9] <= 2.65077162f) {
        votes[3] += 0.877068558f; votes[4] += 0.122931442f;
        return;
      } else {
        votes[4] += 1.0f;
        return;
      }
    }
  }
}

inline void motorV2Tree4(const float features[], float votes[]) {
  if (features[1] <= 2978.92505f) {
    if (features[1] <= 2782.23499f) {
      if (features[6] <= 2758.34998f) {
        if (features[4] <= 1.44029194f) {
          votes[1] += 1.0f;
          return;
        } else {
          if (features[1] <= 2379.32996f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[2] += 0.287454324f; votes[4] += 0.712545676f;
            return;
          }
        }
      } else {
        if (features[10] <= 1385.78168f) {
          votes[1] += 0.541666667f; votes[2] += 0.458333333f;
          return;
        } else {
          if (features[11] <= 1403.64252f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[3] += 0.959349593f; votes[4] += 0.0406504065f;
            return;
          }
        }
      }
    } else {
      if (features[3] <= 1.69219768f) {
        if (features[0] <= 10.8373432f) {
          votes[4] += 1.0f;
          return;
        } else {
          votes[0] += 1.0f;
          return;
        }
      } else {
        if (features[0] <= 10.8578258f) {
          if (features[10] <= 1258.13281f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        } else {
          if (features[9] <= 2.96751142f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[1] += 1.0f;
            return;
          }
        }
      }
    }
  } else {
    if (features[6] <= 3002.55005f) {
      if (features[9] <= 3.43806446f) {
        votes[4] += 1.0f;
        return;
      } else {
        if (features[11] <= 1364.02502f) {
          if (features[6] <= 3001.19995f) {
            votes[2] += 1.0f;
            return;
          } else {
            votes[2] += 0.915912031f; votes[4] += 0.084087969f;
            return;
          }
        } else {
          votes[2] += 0.915912031f; votes[4] += 0.084087969f;
          return;
        }
      }
    } else {
      if (features[4] <= 1.44311064f) {
        votes[4] += 1.0f;
        return;
      } else {
        votes[4] += 1.0f;
        return;
      }
    }
  }
}

inline void motorV2Tree5(const float features[], float votes[]) {
  if (features[0] <= 10.8697205f) {
    if (features[5] <= 2785.39502f) {
      if (features[11] <= 1394.20996f) {
        votes[2] += 1.0f;
        return;
      } else {
        if (features[6] <= 2642.22498f) {
          if (features[0] <= 10.8284373f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[3] += 0.978173719f; votes[4] += 0.0218262806f;
            return;
          }
        } else {
          if (features[11] <= 1463.72003f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    } else {
      if (features[9] <= 3.4205569f) {
        if (features[4] <= 1.47535574f) {
          if (features[1] <= 2939.45007f) {
            votes[0] += 0.927015685f; votes[3] += 0.0656589741f; votes[4] += 0.00732534092f;
            return;
          } else {
            votes[1] += 0.779829545f; votes[4] += 0.220170455f;
            return;
          }
        } else {
          if (features[4] <= 1.64596778f) {
            votes[0] += 0.0450489261f; votes[4] += 0.954951074f;
            return;
          } else {
            votes[0] += 0.515371978f; votes[4] += 0.484628022f;
            return;
          }
        }
      } else {
        if (features[1] <= 2999.77502f) {
          if (features[11] <= 1369.61749f) {
            votes[2] += 0.992957746f; votes[4] += 0.00704225352f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        } else {
          if (features[3] <= 1.78994048f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    }
  } else {
    if (features[7] <= 5.52939987f) {
      if (features[4] <= 1.30609745f) {
        votes[2] += 1.0f;
        return;
      } else {
        if (features[11] <= 1419.72998f) {
          if (features[4] <= 1.40190709f) {
            votes[1] += 1.0f;
            return;
          } else {
            votes[0] += 0.130526316f; votes[1] += 0.869473684f;
            return;
          }
        } else {
          votes[0] += 0.492074162f; votes[1] += 0.468264122f; votes[4] += 0.0396617153f;
          return;
        }
      }
    } else {
      if (features[7] <= 12.79705f) {
        votes[0] += 0.63930131f; votes[4] += 0.36069869f;
        return;
      } else {
        if (features[4] <= 3.7999953f) {
          votes[3] += 1.0f;
          return;
        } else {
          votes[3] += 0.937259923f; votes[4] += 0.0627400768f;
          return;
        }
      }
    }
  }
}

inline void motorV2Tree6(const float features[], float votes[]) {
  if (features[4] <= 1.41212738f) {
    if (features[1] <= 2936.3551f) {
      if (features[5] <= 2786.34253f) {
        if (features[5] <= 2744.11011f) {
          votes[1] += 1.0f;
          return;
        } else {
          votes[1] += 0.379746835f; votes[3] += 0.620253165f;
          return;
        }
      } else {
        if (features[5] <= 2939.66504f) {
          votes[0] += 1.0f;
          return;
        } else {
          votes[0] += 0.281043877f; votes[1] += 0.395755664f; votes[3] += 0.323200459f;
          return;
        }
      }
    } else {
      if (features[6] <= 2972.10498f) {
        votes[1] += 1.0f;
        return;
      } else {
        if (features[10] <= 1366.45337f) {
          votes[2] += 1.0f;
          return;
        } else {
          votes[4] += 1.0f;
          return;
        }
      }
    }
  } else {
    if (features[5] <= 2794.11243f) {
      if (features[3] <= 1.53467399f) {
        votes[3] += 1.0f;
        return;
      } else {
        if (features[7] <= 10.2873001f) {
          if (features[7] <= 5.01824999f) {
            votes[2] += 0.545314506f; votes[4] += 0.454685494f;
            return;
          } else {
            votes[1] += 0.947537473f; votes[4] += 0.0524625268f;
            return;
          }
        } else {
          votes[3] += 1.0f;
          return;
        }
      }
    } else {
      if (features[1] <= 2978.92505f) {
        if (features[0] <= 10.8460793f) {
          if (features[6] <= 2991.03491f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[2] += 0.283835792f; votes[3] += 0.5463839f; votes[4] += 0.169780308f;
            return;
          }
        } else {
          if (features[0] <= 10.8750534f) {
            votes[0] += 0.841066561f; votes[2] += 0.150736604f; votes[4] += 0.00819683512f;
            return;
          } else {
            votes[0] += 0.170135885f; votes[1] += 0.239579103f; votes[3] += 0.391312536f; votes[4] += 0.198972476f;
            return;
          }
        }
      } else {
        if (features[5] <= 3000.86243f) {
          if (features[8] <= 3.35164702f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[2] += 0.986587702f; votes[4] += 0.0134122975f;
            return;
          }
        } else {
          if (features[0] <= 10.7707334f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    }
  }
}

inline void motorV2Tree7(const float features[], float votes[]) {
  if (features[0] <= 10.8436751f) {
    if (features[9] <= 3.4205569f) {
      if (features[2] <= 1.5612185f) {
        if (features[3] <= 1.5354594f) {
          votes[3] += 1.0f;
          return;
        } else {
          if (features[7] <= 4.62260008f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[3] += 0.967257844f; votes[4] += 0.0327421555f;
            return;
          }
        }
      } else {
        if (features[7] <= 11.0977502f) {
          if (features[4] <= 1.4043839f) {
            votes[1] += 0.776560789f; votes[4] += 0.223439211f;
            return;
          } else {
            votes[2] += 0.0198471573f; votes[4] += 0.980152843f;
            return;
          }
        } else {
          if (features[10] <= 1420.91077f) {
            votes[3] += 0.975240715f; votes[4] += 0.0247592847f;
            return;
          } else {
            votes[0] += 0.716885743f; votes[4] += 0.283114257f;
            return;
          }
        }
      }
    } else {
      if (features[2] <= 1.8386324f) {
        if (features[7] <= 4.88240004f) {
          if (features[0] <= 10.789762f) {
            votes[2] += 1.0f;
            return;
          } else {
            votes[2] += 0.563593005f; votes[4] += 0.436406995f;
            return;
          }
        } else {
          if (features[8] <= 3.49149704f) {
            votes[2] += 0.983083749f; votes[4] += 0.0169162507f;
            return;
          } else {
            votes[2] += 1.0f;
            return;
          }
        }
      } else {
        if (features[7] <= 5.75084996f) {
          if (features[6] <= 3031.44995f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        } else {
          votes[2] += 0.853188929f; votes[4] += 0.146811071f;
          return;
        }
      }
    }
  } else {
    if (features[0] <= 10.8675146f) {
      if (features[9] <= 3.15945816f) {
        if (features[5] <= 2799.81494f) {
          votes[0] += 0.606741573f; votes[3] += 0.393258427f;
          return;
        } else {
          if (features[10] <= 1427.92712f) {
            votes[0] += 1.0f;
            return;
          } else {
            votes[0] += 0.910141207f; votes[4] += 0.0898587933f;
            return;
          }
        }
      } else {
        if (features[1] <= 2998.27502f) {
          if (features[11] <= 1345.24249f) {
            votes[1] += 0.374233129f; votes[2] += 0.625766871f;
            return;
          } else {
            votes[2] += 1.0f;
            return;
          }
        } else {
          if (features[9] <= 3.37335157f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    } else {
      if (features[5] <= 2978.63501f) {
        if (features[6] <= 3589.37988f) {
          if (features[11] <= 1420.79999f) {
            votes[0] += 0.0552467546f; votes[1] += 0.928903767f; votes[2] += 0.0158494788f;
            return;
          } else {
            votes[0] += 0.669499528f; votes[4] += 0.330500472f;
            return;
          }
        } else {
          if (features[6] <= 4915.81494f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[3] += 1.0f;
            return;
          }
        }
      } else {
        if (features[10] <= 1359.22821f) {
          if (features[0] <= 10.8898058f) {
            votes[2] += 1.0f;
            return;
          } else {
            votes[2] += 1.0f;
            return;
          }
        } else {
          votes[2] += 0.662406166f; votes[3] += 0.280602612f; votes[4] += 0.0569912216f;
          return;
        }
      }
    }
  }
}

inline void motorV2Tree8(const float features[], float votes[]) {
  if (features[8] <= 3.45078504f) {
    if (features[0] <= 10.8435922f) {
      if (features[7] <= 4.87639999f) {
        if (features[10] <= 1463.37268f) {
          if (features[9] <= 2.25303149f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[3] += 0.93129771f; votes[4] += 0.0687022901f;
            return;
          }
        } else {
          if (features[1] <= 2521.16992f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      } else {
        if (features[5] <= 2799.68005f) {
          if (features[10] <= 1419.76031f) {
            votes[2] += 0.281984334f; votes[3] += 0.718015666f;
            return;
          } else {
            votes[0] += 0.554545455f; votes[4] += 0.445454545f;
            return;
          }
        } else {
          if (features[6] <= 3344.42004f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[3] += 0.772151899f; votes[4] += 0.227848101f;
            return;
          }
        }
      }
    } else {
      if (features[3] <= 1.69618756f) {
        if (features[9] <= 2.22558725f) {
          if (features[11] <= 1408.29248f) {
            votes[1] += 0.647139389f; votes[2] += 0.174811679f; votes[3] += 0.178048932f;
            return;
          } else {
            votes[1] += 1.0f;
            return;
          }
        } else {
          if (features[1] <= 2787.71497f) {
            votes[0] += 0.433005299f; votes[1] += 0.291445874f; votes[2] += 0.275548827f;
            return;
          } else {
            votes[0] += 1.0f;
            return;
          }
        }
      } else {
        if (features[10] <= 1388.77423f) {
          if (features[7] <= 5.24324989f) {
            votes[1] += 0.760368664f; votes[2] += 0.239631336f;
            return;
          } else {
            votes[1] += 1.0f;
            return;
          }
        } else {
          if (features[11] <= 1419.14252f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    }
  } else {
    if (features[6] <= 3002.4751f) {
      if (features[10] <= 1363.56482f) {
        if (features[6] <= 3001.34998f) {
          if (features[2] <= 1.63363343f) {
            votes[2] += 1.0f;
            return;
          } else {
            votes[2] += 1.0f;
            return;
          }
        } else {
          votes[2] += 0.975566415f; votes[4] += 0.0244335851f;
          return;
        }
      } else {
        votes[2] += 0.930114358f; votes[4] += 0.0698856417f;
        return;
      }
    } else {
      if (features[0] <= 10.7912531f) {
        votes[4] += 1.0f;
        return;
      } else {
        votes[4] += 1.0f;
        return;
      }
    }
  }
}

inline void motorV2Tree9(const float features[], float votes[]) {
  if (features[9] <= 3.4205569f) {
    if (features[4] <= 1.41210729f) {
      if (features[11] <= 1382.26752f) {
        if (features[0] <= 10.8614211f) {
          votes[0] += 1.0f;
          return;
        } else {
          if (features[2] <= 1.69235486f) {
            votes[0] += 0.277777778f; votes[1] += 0.722222222f;
            return;
          } else {
            votes[1] += 1.0f;
            return;
          }
        }
      } else {
        if (features[1] <= 2788.31006f) {
          votes[1] += 0.565217391f; votes[3] += 0.434782609f;
          return;
        } else {
          if (features[1] <= 2961.83997f) {
            votes[0] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    } else {
      if (features[0] <= 10.8293781f) {
        if (features[5] <= 2785.39502f) {
          if (features[11] <= 1463.41748f) {
            votes[2] += 0.0666666667f; votes[3] += 0.933333333f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        } else {
          if (features[3] <= 2.89072859f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[3] += 0.846698113f; votes[4] += 0.153301887f;
            return;
          }
        }
      } else {
        if (features[2] <= 1.53467399f) {
          votes[3] += 1.0f;
          return;
        } else {
          if (features[7] <= 12.79705f) {
            votes[0] += 0.253971498f; votes[1] += 0.256793404f; votes[2] += 0.310409609f; votes[4] += 0.17882549f;
            return;
          } else {
            votes[3] += 0.986263736f; votes[4] += 0.0137362637f;
            return;
          }
        }
      }
    }
  } else {
    if (features[7] <= 5.21700001f) {
      if (features[6] <= 3001.65002f) {
        if (features[10] <= 1363.54639f) {
          votes[2] += 1.0f;
          return;
        } else {
          votes[2] += 0.688398849f; votes[4] += 0.311601151f;
          return;
        }
      } else {
        votes[4] += 1.0f;
        return;
      }
    } else {
      if (features[1] <= 2999.40002f) {
        votes[2] += 0.846698113f; votes[4] += 0.153301887f;
        return;
      } else {
        votes[4] += 1.0f;
        return;
      }
    }
  }
}

inline void motorV2Tree10(const float features[], float votes[]) {
  if (features[0] <= 10.8439202f) {
    if (features[3] <= 1.55640441f) {
      if (features[11] <= 1403.07996f) {
        votes[3] += 1.0f;
        return;
      } else {
        votes[3] += 0.807865169f; votes[4] += 0.192134831f;
        return;
      }
    } else {
      if (features[8] <= 3.41068423f) {
        if (features[1] <= 2415.75f) {
          votes[3] += 1.0f;
          return;
        } else {
          if (features[7] <= 5.00740004f) {
            votes[1] += 0.129021508f; votes[2] += 0.147453152f; votes[4] += 0.72352534f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      } else {
        if (features[6] <= 3002.02502f) {
          if (features[1] <= 2995.28491f) {
            votes[2] += 1.0f;
            return;
          } else {
            votes[2] += 0.980900409f; votes[4] += 0.0190995907f;
            return;
          }
        } else {
          votes[4] += 1.0f;
          return;
        }
      }
    }
  } else {
    if (features[5] <= 2972.68506f) {
      if (features[6] <= 2940.52502f) {
        if (features[8] <= 2.19801402f) {
          if (features[6] <= 2738.66504f) {
            votes[1] += 0.466666667f; votes[2] += 0.533333333f;
            return;
          } else {
            votes[1] += 0.978231293f; votes[4] += 0.0217687075f;
            return;
          }
        } else {
          if (features[2] <= 1.69746602f) {
            votes[0] += 1.0f;
            return;
          } else {
            votes[1] += 0.651858568f; votes[4] += 0.348141432f;
            return;
          }
        }
      } else {
        if (features[11] <= 1385.81494f) {
          if (features[0] <= 10.8682933f) {
            votes[0] += 0.323232323f; votes[1] += 0.676767677f;
            return;
          } else {
            votes[1] += 1.0f;
            return;
          }
        } else {
          if (features[4] <= 2.43573833f) {
            votes[1] += 0.30209925f; votes[2] += 0.345256285f; votes[3] += 0.339199158f; votes[4] += 0.0134453074f;
            return;
          } else {
            votes[3] += 1.0f;
            return;
          }
        }
      }
    } else {
      if (features[10] <= 1389.32214f) {
        if (features[2] <= 1.77177781f) {
          if (features[1] <= 2983.58997f) {
            votes[2] += 1.0f;
            return;
          } else {
            votes[2] += 1.0f;
            return;
          }
        } else {
          votes[2] += 0.927741935f; votes[4] += 0.0722580645f;
          return;
        }
      } else {
        if (features[5] <= 3018.48999f) {
          votes[4] += 1.0f;
          return;
        } else {
          votes[3] += 0.893722809f; votes[4] += 0.106277191f;
          return;
        }
      }
    }
  }
}

inline void motorV2Tree11(const float features[], float votes[]) {
  if (features[8] <= 3.4205569f) {
    if (features[0] <= 10.8437233f) {
      if (features[2] <= 1.53467399f) {
        votes[3] += 1.0f;
        return;
      } else {
        if (features[3] <= 1.62448275f) {
          if (features[6] <= 2680.05994f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[1] += 0.155566629f; votes[2] += 0.674122058f; votes[3] += 0.0856934819f; votes[4] += 0.0846178315f;
            return;
          }
        } else {
          if (features[5] <= 2785.01001f) {
            votes[3] += 0.676925982f; votes[4] += 0.323074018f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    } else {
      if (features[7] <= 5.21880007f) {
        if (features[8] <= 2.11110526f) {
          if (features[5] <= 2737.66504f) {
            votes[1] += 0.644808743f; votes[3] += 0.355191257f;
            return;
          } else {
            votes[1] += 1.0f;
            return;
          }
        } else {
          if (features[8] <= 3.12647796f) {
            votes[0] += 0.983342289f; votes[2] += 0.0166577109f;
            return;
          } else {
            votes[0] += 0.238864643f; votes[2] += 0.740480394f; votes[4] += 0.0206549622f;
            return;
          }
        }
      } else {
        if (features[1] <= 2531.63f) {
          votes[3] += 1.0f;
          return;
        } else {
          if (features[11] <= 1385.30499f) {
            votes[1] += 1.0f;
            return;
          } else {
            votes[1] += 0.367928159f; votes[2] += 0.398588839f; votes[4] += 0.233483002f;
            return;
          }
        }
      }
    }
  } else {
    if (features[11] <= 1364.31f) {
      if (features[6] <= 3003.07996f) {
        if (features[1] <= 2996.33008f) {
          votes[2] += 1.0f;
          return;
        } else {
          if (features[6] <= 3001.34998f) {
            votes[2] += 1.0f;
            return;
          } else {
            votes[2] += 0.922779923f; votes[4] += 0.0772200772f;
            return;
          }
        }
      } else {
        if (features[2] <= 1.84865487f) {
          votes[4] += 1.0f;
          return;
        } else {
          votes[4] += 1.0f;
          return;
        }
      }
    } else {
      if (features[3] <= 1.73817557f) {
        votes[4] += 1.0f;
        return;
      } else {
        votes[4] += 1.0f;
        return;
      }
    }
  }
}

inline void motorV2Tree12(const float features[], float votes[]) {
  if (features[2] <= 1.52869421f) {
    votes[3] += 1.0f;
    return;
  } else {
    if (features[8] <= 3.45204186f) {
      if (features[3] <= 1.69215512f) {
        if (features[7] <= 4.93924999f) {
          if (features[6] <= 2676.0f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[2] += 0.754448399f; votes[3] += 0.245551601f;
            return;
          }
        } else {
          if (features[1] <= 2765.41504f) {
            votes[1] += 0.653884746f; votes[2] += 0.280953037f; votes[4] += 0.0651622169f;
            return;
          } else {
            votes[0] += 0.914327624f; votes[4] += 0.0856723761f;
            return;
          }
        }
      } else {
        if (features[3] <= 1.73786789f) {
          if (features[9] <= 2.65861392f) {
            votes[3] += 0.262751159f; votes[4] += 0.737248841f;
            return;
          } else {
            votes[1] += 0.981380915f; votes[2] += 0.0186190846f;
            return;
          }
        } else {
          if (features[5] <= 2787.57251f) {
            votes[3] += 0.991414223f; votes[4] += 0.00858577677f;
            return;
          } else {
            votes[0] += 0.0176739182f; votes[3] += 0.0593576874f; votes[4] += 0.922968394f;
            return;
          }
        }
      }
    } else {
      if (features[5] <= 3001.27502f) {
        if (features[11] <= 1368.20752f) {
          if (features[5] <= 2997.82507f) {
            votes[2] += 1.0f;
            return;
          } else {
            votes[2] += 0.977948226f; votes[4] += 0.0220517737f;
            return;
          }
        } else {
          votes[4] += 1.0f;
          return;
        }
      } else {
        votes[4] += 1.0f;
        return;
      }
    }
  }
}

inline void motorV2Tree13(const float features[], float votes[]) {
  if (features[8] <= 3.4205569f) {
    if (features[1] <= 2785.13f) {
      if (features[4] <= 1.40048516f) {
        votes[1] += 1.0f;
        return;
      } else {
        if (features[3] <= 1.55640441f) {
          if (features[3] <= 1.53467399f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[2] += 0.161644072f; votes[3] += 0.737501079f; votes[4] += 0.100854848f;
            return;
          }
        } else {
          if (features[1] <= 2420.42493f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[1] += 0.456038459f; votes[2] += 0.210839698f; votes[3] += 0.0480978062f; votes[4] += 0.285024037f;
            return;
          }
        }
      }
    } else {
      if (features[7] <= 5.17510009f) {
        if (features[0] <= 10.8375878f) {
          votes[4] += 1.0f;
          return;
        } else {
          if (features[10] <= 1436.37079f) {
            votes[0] += 1.0f;
            return;
          } else {
            votes[0] += 0.909326425f; votes[4] += 0.0906735751f;
            return;
          }
        }
      } else {
        if (features[4] <= 1.40772152f) {
          if (features[0] <= 10.8544903f) {
            votes[0] += 0.8004561f; votes[4] += 0.1995439f;
            return;
          } else {
            votes[1] += 1.0f;
            return;
          }
        } else {
          if (features[3] <= 1.64687669f) {
            votes[0] += 0.882648785f; votes[4] += 0.117351215f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    }
  } else {
    if (features[6] <= 3002.55005f) {
      if (features[11] <= 1344.26251f) {
        votes[2] += 0.905806452f; votes[4] += 0.0941935484f;
        return;
      } else {
        if (features[11] <= 1364.27002f) {
          votes[2] += 1.0f;
          return;
        } else {
          votes[2] += 0.935168739f; votes[4] += 0.0648312611f;
          return;
        }
      }
    } else {
      votes[4] += 1.0f;
      return;
    }
  }
}

inline void motorV2Tree14(const float features[], float votes[]) {
  if (features[3] <= 1.53467399f) {
    votes[3] += 1.0f;
    return;
  } else {
    if (features[5] <= 2981.55261f) {
      if (features[0] <= 10.8671489f) {
        if (features[0] <= 10.8435922f) {
          if (features[7] <= 7.77579975f) {
            votes[1] += 0.0219773359f; votes[2] += 0.0589392189f; votes[4] += 0.919083445f;
            return;
          } else {
            votes[0] += 0.259935142f; votes[3] += 0.695203893f; votes[4] += 0.0448609655f;
            return;
          }
        } else {
          if (features[7] <= 5.2253499f) {
            votes[0] += 0.981184669f; votes[2] += 0.018815331f;
            return;
          } else {
            votes[0] += 0.409182369f; votes[1] += 0.280879423f; votes[2] += 0.251089181f; votes[4] += 0.0588490268f;
            return;
          }
        }
      } else {
        if (features[4] <= 2.31725097f) {
          if (features[2] <= 1.60326695f) {
            votes[0] += 1.0f;
            return;
          } else {
            votes[0] += 0.0247175933f; votes[1] += 0.950161046f; votes[2] += 0.0151676141f; votes[4] += 0.00995374675f;
            return;
          }
        } else {
          if (features[10] <= 1412.49835f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    } else {
      if (features[3] <= 1.8386324f) {
        if (features[5] <= 3000.86243f) {
          if (features[3] <= 1.75023824f) {
            votes[2] += 0.997920998f; votes[4] += 0.00207900208f;
            return;
          } else {
            votes[2] += 0.907216495f; votes[4] += 0.0927835052f;
            return;
          }
        } else {
          if (features[6] <= 3008.125f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[3] += 0.92998679f; votes[4] += 0.07001321f;
            return;
          }
        }
      } else {
        if (features[1] <= 2990.94995f) {
          if (features[8] <= 2.80215168f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[2] += 0.888888889f; votes[4] += 0.111111111f;
            return;
          }
        } else {
          votes[4] += 1.0f;
          return;
        }
      }
    }
  }
}

inline void motorV2Tree15(const float features[], float votes[]) {
  if (features[2] <= 1.56179041f) {
    if (features[11] <= 1471.25751f) {
      votes[3] += 1.0f;
      return;
    } else {
      if (features[5] <= 2540.59998f) {
        votes[4] += 1.0f;
        return;
      } else {
        votes[4] += 1.0f;
        return;
      }
    }
  } else {
    if (features[8] <= 3.41068423f) {
      if (features[0] <= 10.8435922f) {
        if (features[6] <= 3916.33008f) {
          if (features[4] <= 2.25215662f) {
            votes[2] += 0.0157599638f; votes[3] += 0.0188602845f; votes[4] += 0.965379752f;
            return;
          } else {
            votes[2] += 0.663904236f; votes[4] += 0.336095764f;
            return;
          }
        } else {
          if (features[1] <= 2314.1001f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[3] += 0.921994885f; votes[4] += 0.0780051151f;
            return;
          }
        }
      } else {
        if (features[2] <= 1.69585264f) {
          if (features[9] <= 2.21637869f) {
            votes[1] += 0.917414722f; votes[2] += 0.0825852783f;
            return;
          } else {
            votes[0] += 0.880209699f; votes[1] += 0.0956749672f; votes[2] += 0.0241153342f;
            return;
          }
        } else {
          if (features[10] <= 1388.77423f) {
            votes[1] += 1.0f;
            return;
          } else {
            votes[3] += 0.716937355f; votes[4] += 0.283062645f;
            return;
          }
        }
      }
    } else {
      if (features[4] <= 1.55050743f) {
        if (features[10] <= 1368.20374f) {
          if (features[5] <= 2999.84998f) {
            votes[2] += 1.0f;
            return;
          } else {
            votes[2] += 0.908060453f; votes[4] += 0.0919395466f;
            return;
          }
        } else {
          if (features[7] <= 4.87575006f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      } else {
        if (features[11] <= 1330.935f) {
          votes[4] += 1.0f;
          return;
        } else {
          votes[4] += 1.0f;
          return;
        }
      }
    }
  }
}

inline void motorV2Tree16(const float features[], float votes[]) {
  if (features[9] <= 3.45529795f) {
    if (features[6] <= 3067.17505f) {
      if (features[0] <= 10.8436007f) {
        if (features[3] <= 1.56179041f) {
          if (features[9] <= 1.18030399f) {
            votes[3] += 0.871428571f; votes[4] += 0.128571429f;
            return;
          } else {
            votes[3] += 1.0f;
            return;
          }
        } else {
          if (features[3] <= 2.35010719f) {
            votes[1] += 0.0364551919f; votes[2] += 0.041855961f; votes[4] += 0.921688847f;
            return;
          } else {
            votes[0] += 0.782608696f; votes[4] += 0.217391304f;
            return;
          }
        }
      } else {
        if (features[0] <= 10.8634005f) {
          if (features[9] <= 2.24978483f) {
            votes[0] += 0.469565217f; votes[2] += 0.530434783f;
            return;
          } else {
            votes[0] += 0.983606557f; votes[4] += 0.0163934426f;
            return;
          }
        } else {
          if (features[3] <= 1.60199243f) {
            votes[0] += 0.639053254f; votes[2] += 0.360946746f;
            return;
          } else {
            votes[0] += 0.0744880614f; votes[1] += 0.879439693f; votes[2] += 0.0336575685f; votes[4] += 0.0124146769f;
            return;
          }
        }
      }
    } else {
      if (features[5] <= 2795.26501f) {
        if (features[10] <= 1403.48663f) {
          votes[3] += 1.0f;
          return;
        } else {
          votes[3] += 0.871428571f; votes[4] += 0.128571429f;
          return;
        }
      } else {
        if (features[1] <= 2925.97009f) {
          votes[4] += 1.0f;
          return;
        } else {
          votes[4] += 1.0f;
          return;
        }
      }
    }
  } else {
    if (features[1] <= 2999.77502f) {
      if (features[11] <= 1369.61749f) {
        if (features[6] <= 3001.34998f) {
          votes[2] += 1.0f;
          return;
        } else {
          votes[2] += 0.947572816f; votes[4] += 0.0524271845f;
          return;
        }
      } else {
        votes[4] += 1.0f;
        return;
      }
    } else {
      if (features[0] <= 10.7918563f) {
        votes[4] += 1.0f;
        return;
      } else {
        votes[4] += 1.0f;
        return;
      }
    }
  }
}

inline void motorV2Tree17(const float features[], float votes[]) {
  if (features[9] <= 3.45401251f) {
    if (features[4] <= 1.41210729f) {
      if (features[0] <= 10.8732033f) {
        if (features[2] <= 1.69618756f) {
          if (features[10] <= 1417.07855f) {
            votes[0] += 1.0f;
            return;
          } else {
            votes[0] += 0.874100719f; votes[1] += 0.125899281f;
            return;
          }
        } else {
          if (features[1] <= 2944.06006f) {
            votes[1] += 0.329192547f; votes[3] += 0.670807453f;
            return;
          } else {
            votes[1] += 0.872037915f; votes[4] += 0.127962085f;
            return;
          }
        }
      } else {
        if (features[6] <= 2960.69507f) {
          votes[1] += 1.0f;
          return;
        } else {
          votes[1] += 0.93164557f; votes[4] += 0.0683544304f;
          return;
        }
      }
    } else {
      if (features[2] <= 1.53467399f) {
        votes[3] += 1.0f;
        return;
      } else {
        if (features[6] <= 3916.33008f) {
          if (features[0] <= 10.8459115f) {
            votes[2] += 0.0640885358f; votes[3] += 0.0201536276f; votes[4] += 0.915757837f;
            return;
          } else {
            votes[0] += 0.517760955f; votes[1] += 0.258142926f; votes[2] += 0.167276616f; votes[4] += 0.0568195028f;
            return;
          }
        } else {
          if (features[10] <= 1423.62341f) {
            votes[3] += 0.995222212f; votes[4] += 0.00477778779f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    }
  } else {
    if (features[4] <= 1.55119336f) {
      if (features[11] <= 1368.20752f) {
        if (features[1] <= 2998.27502f) {
          if (features[10] <= 1344.61749f) {
            votes[2] += 0.967148489f; votes[4] += 0.0328515112f;
            return;
          } else {
            votes[2] += 1.0f;
            return;
          }
        } else {
          votes[2] += 0.956672444f; votes[4] += 0.0433275563f;
          return;
        }
      } else {
        votes[4] += 1.0f;
        return;
      }
    } else {
      if (features[10] <= 1349.13635f) {
        votes[4] += 1.0f;
        return;
      } else {
        votes[4] += 1.0f;
        return;
      }
    }
  }
}

inline void motorV2Tree18(const float features[], float votes[]) {
  if (features[1] <= 2978.92505f) {
    if (features[1] <= 2782.23499f) {
      if (features[10] <= 1412.86243f) {
        if (features[10] <= 1388.7533f) {
          votes[1] += 0.791044776f; votes[2] += 0.208955224f;
          return;
        } else {
          if (features[5] <= 2797.79993f) {
            votes[2] += 0.0198883461f; votes[3] += 0.980111654f;
            return;
          } else {
            votes[1] += 0.337278107f; votes[3] += 0.662721893f;
            return;
          }
        }
      } else {
        if (features[11] <= 1471.47998f) {
          votes[1] += 1.0f;
          return;
        } else {
          if (features[4] <= 2.05033088f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    } else {
      if (features[1] <= 2936.28503f) {
        if (features[0] <= 10.8429055f) {
          if (features[4] <= 1.47185946f) {
            votes[0] += 0.944370861f; votes[4] += 0.0556291391f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        } else {
          if (features[7] <= 6.66190004f) {
            votes[0] += 0.994143893f; votes[4] += 0.00585610708f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      } else {
        if (features[0] <= 10.8541708f) {
          votes[4] += 1.0f;
          return;
        } else {
          if (features[11] <= 1381.43994f) {
            votes[1] += 1.0f;
            return;
          } else {
            votes[1] += 0.974487472f; votes[4] += 0.0255125285f;
            return;
          }
        }
      }
    }
  } else {
    if (features[5] <= 3000.86243f) {
      if (features[11] <= 1369.61749f) {
        if (features[11] <= 1323.97504f) {
          votes[4] += 1.0f;
          return;
        } else {
          votes[2] += 1.0f;
          return;
        }
      } else {
        if (features[2] <= 1.75412488f) {
          votes[4] += 1.0f;
          return;
        } else {
          votes[4] += 1.0f;
          return;
        }
      }
    } else {
      votes[4] += 1.0f;
      return;
    }
  }
}

inline void motorV2Tree19(const float features[], float votes[]) {
  if (features[8] <= 3.4205569f) {
    if (features[5] <= 2794.14502f) {
      if (features[4] <= 1.40005839f) {
        if (features[6] <= 2748.13489f) {
          votes[1] += 1.0f;
          return;
        } else {
          votes[0] += 0.314136126f; votes[1] += 0.371727749f; votes[3] += 0.314136126f;
          return;
        }
      } else {
        if (features[11] <= 1394.20996f) {
          if (features[8] <= 2.11880302f) {
            votes[1] += 0.347826087f; votes[2] += 0.652173913f;
            return;
          } else {
            votes[2] += 1.0f;
            return;
          }
        } else {
          if (features[2] <= 1.5354594f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[2] += 0.0622109417f; votes[3] += 0.560774686f; votes[4] += 0.377014373f;
            return;
          }
        }
      }
    } else {
      if (features[2] <= 1.69219768f) {
        if (features[8] <= 2.23864031f) {
          if (features[8] <= 2.19058061f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[3] += 0.830750894f; votes[4] += 0.169249106f;
            return;
          }
        } else {
          if (features[11] <= 1437.41498f) {
            votes[0] += 0.969328026f; votes[1] += 0.0166237415f; votes[3] += 0.0140482323f;
            return;
          } else {
            votes[0] += 0.662547529f; votes[4] += 0.337452471f;
            return;
          }
        }
      } else {
        if (features[4] <= 1.39979678f) {
          if (features[11] <= 1381.8075f) {
            votes[1] += 1.0f;
            return;
          } else {
            votes[1] += 0.853121175f; votes[4] += 0.146878825f;
            return;
          }
        } else {
          if (features[6] <= 4468.13f) {
            votes[1] += 0.045894515f; votes[4] += 0.954105485f;
            return;
          } else {
            votes[3] += 1.0f;
            return;
          }
        }
      }
    }
  } else {
    if (features[6] <= 3003.07996f) {
      if (features[10] <= 1364.02411f) {
        if (features[5] <= 2999.92493f) {
          votes[2] += 1.0f;
          return;
        } else {
          votes[2] += 0.956104252f; votes[4] += 0.0438957476f;
          return;
        }
      } else {
        votes[2] += 0.844848485f; votes[4] += 0.155151515f;
        return;
      }
    } else {
      votes[4] += 1.0f;
      return;
    }
  }
}

inline void motorV2Tree20(const float features[], float votes[]) {
  if (features[9] <= 3.4205569f) {
    if (features[4] <= 1.41130865f) {
      if (features[7] <= 5.20740008f) {
        if (features[5] <= 2768.99255f) {
          votes[1] += 1.0f;
          return;
        } else {
          if (features[7] <= 4.95834994f) {
            votes[0] += 0.636363636f; votes[3] += 0.363636364f;
            return;
          } else {
            votes[0] += 1.0f;
            return;
          }
        }
      } else {
        if (features[6] <= 2978.51001f) {
          votes[1] += 1.0f;
          return;
        } else {
          if (features[0] <= 10.8243194f) {
            votes[3] += 0.927083333f; votes[4] += 0.0729166667f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    } else {
      if (features[1] <= 2782.23499f) {
        if (features[6] <= 2755.65002f) {
          if (features[5] <= 2492.72998f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[1] += 0.194176775f; votes[2] += 0.314381445f; votes[4] += 0.491441781f;
            return;
          }
        } else {
          if (features[2] <= 1.57551473f) {
            votes[3] += 1.0f;
            return;
          } else {
            votes[1] += 0.128787502f; votes[2] += 0.185344976f; votes[3] += 0.677667569f; votes[4] += 0.0081999533f;
            return;
          }
        }
      } else {
        if (features[3] <= 1.67991513f) {
          if (features[5] <= 2871.81006f) {
            votes[0] += 0.326007326f; votes[4] += 0.673992674f;
            return;
          } else {
            votes[0] += 1.0f;
            return;
          }
        } else {
          if (features[1] <= 2802.43005f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    }
  } else {
    if (features[6] <= 3003.07996f) {
      if (features[11] <= 1367.92499f) {
        if (features[10] <= 1344.27802f) {
          votes[2] += 0.918709677f; votes[4] += 0.0812903226f;
          return;
        } else {
          if (features[11] <= 1345.29498f) {
            votes[2] += 1.0f;
            return;
          } else {
            votes[2] += 1.0f;
            return;
          }
        }
      } else {
        votes[4] += 1.0f;
        return;
      }
    } else {
      if (features[7] <= 5.36720014f) {
        votes[4] += 1.0f;
        return;
      } else {
        votes[4] += 1.0f;
        return;
      }
    }
  }
}

inline void motorV2Tree21(const float features[], float votes[]) {
  if (features[1] <= 2785.13f) {
    if (features[11] <= 1394.46246f) {
      if (features[6] <= 2972.64001f) {
        votes[1] += 0.861650485f; votes[2] += 0.138349515f;
        return;
      } else {
        votes[2] += 1.0f;
        return;
      }
    } else {
      if (features[5] <= 2757.79504f) {
        if (features[3] <= 1.52745813f) {
          votes[3] += 1.0f;
          return;
        } else {
          if (features[10] <= 1471.62396f) {
            votes[1] += 0.594572832f; votes[2] += 0.0795555198f; votes[3] += 0.325871648f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      } else {
        votes[3] += 1.0f;
        return;
      }
    }
  } else {
    if (features[4] <= 1.54864585f) {
      if (features[7] <= 5.21994996f) {
        if (features[10] <= 1367.15063f) {
          if (features[5] <= 3000.86243f) {
            votes[2] += 0.994786312f; votes[4] += 0.00521368777f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        } else {
          if (features[9] <= 2.18348241f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[0] += 0.993603363f; votes[4] += 0.0063966372f;
            return;
          }
        }
      } else {
        if (features[11] <= 1383.06494f) {
          if (features[2] <= 1.76328689f) {
            votes[1] += 1.0f;
            return;
          } else {
            votes[2] += 0.715145436f; votes[4] += 0.284854564f;
            return;
          }
        } else {
          if (features[2] <= 1.97804189f) {
            votes[0] += 0.187977854f; votes[4] += 0.812022146f;
            return;
          } else {
            votes[0] += 0.910600255f; votes[4] += 0.0893997446f;
            return;
          }
        }
      }
    } else {
      if (features[0] <= 10.8490982f) {
        if (features[0] <= 10.769196f) {
          if (features[0] <= 10.7630043f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[2] += 0.715145436f; votes[4] += 0.284854564f;
            return;
          }
        } else {
          if (features[1] <= 2790.375f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      } else {
        if (features[3] <= 1.69841832f) {
          votes[0] += 0.980742779f; votes[4] += 0.0192572215f;
          return;
        } else {
          if (features[5] <= 2828.25f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        }
      }
    }
  }
}

inline void motorV2Tree22(const float features[], float votes[]) {
  if (features[9] <= 3.4205569f) {
    if (features[5] <= 2794.14502f) {
      if (features[10] <= 1403.44379f) {
        if (features[0] <= 10.845624f) {
          if (features[11] <= 1395.98749f) {
            votes[2] += 0.597402597f; votes[3] += 0.402597403f;
            return;
          } else {
            votes[3] += 1.0f;
            return;
          }
        } else {
          if (features[4] <= 1.96822995f) {
            votes[1] += 0.567765568f; votes[2] += 0.432234432f;
            return;
          } else {
            votes[3] += 1.0f;
            return;
          }
        }
      } else {
        if (features[8] <= 1.53693998f) {
          votes[4] += 1.0f;
          return;
        } else {
          if (features[5] <= 2767.53003f) {
            votes[1] += 0.904376013f; votes[2] += 0.095623987f;
            return;
          } else {
            votes[0] += 0.679558011f; votes[4] += 0.320441989f;
            return;
          }
        }
      }
    } else {
      if (features[2] <= 1.69219768f) {
        if (features[11] <= 1455.5025f) {
          if (features[1] <= 2794.27502f) {
            votes[0] += 0.670454545f; votes[1] += 0.329545455f;
            return;
          } else {
            votes[0] += 1.0f;
            return;
          }
        } else {
          votes[4] += 1.0f;
          return;
        }
      } else {
        if (features[11] <= 1382.56744f) {
          if (features[2] <= 1.75710428f) {
            votes[1] += 0.937741822f; votes[2] += 0.062258178f;
            return;
          } else {
            votes[4] += 1.0f;
            return;
          }
        } else {
          if (features[7] <= 12.79705f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[0] += 0.182151825f; votes[3] += 0.689009079f; votes[4] += 0.128839096f;
            return;
          }
        }
      }
    }
  } else {
    if (features[5] <= 3000.86243f) {
      if (features[11] <= 1369.61749f) {
        if (features[9] <= 3.60394943f) {
          if (features[4] <= 1.53752202f) {
            votes[2] += 0.959687906f; votes[4] += 0.0403120936f;
            return;
          } else {
            votes[2] += 1.0f;
            return;
          }
        } else {
          votes[2] += 1.0f;
          return;
        }
      } else {
        votes[4] += 1.0f;
        return;
      }
    } else {
      votes[4] += 1.0f;
      return;
    }
  }
}

inline void motorV2Tree23(const float features[], float votes[]) {
  if (features[1] <= 2978.92505f) {
    if (features[0] <= 10.8435922f) {
      if (features[3] <= 1.55653661f) {
        if (features[3] <= 1.53289485f) {
          votes[3] += 1.0f;
          return;
        } else {
          votes[3] += 0.908268734f; votes[4] += 0.0917312661f;
          return;
        }
      } else {
        if (features[7] <= 9.83000016f) {
          if (features[6] <= 2990.36499f) {
            votes[1] += 0.0645763802f; votes[4] += 0.93542362f;
            return;
          } else {
            votes[2] += 0.829335431f; votes[4] += 0.170664569f;
            return;
          }
        } else {
          if (features[0] <= 10.784059f) {
            votes[3] += 0.895629165f; votes[4] += 0.104370835f;
            return;
          } else {
            votes[0] += 0.364102564f; votes[3] += 0.635897436f;
            return;
          }
        }
      }
    } else {
      if (features[5] <= 2937.86499f) {
        if (features[5] <= 2786.60254f) {
          if (features[2] <= 1.58304113f) {
            votes[2] += 0.604255319f; votes[3] += 0.395744681f;
            return;
          } else {
            votes[1] += 0.792589851f; votes[2] += 0.0461633874f; votes[3] += 0.161246762f;
            return;
          }
        } else {
          if (features[3] <= 1.73732203f) {
            votes[0] += 0.998532266f; votes[4] += 0.00146773354f;
            return;
          } else {
            votes[3] += 0.712259372f; votes[4] += 0.287740628f;
            return;
          }
        }
      } else {
        if (features[4] <= 1.39725041f) {
          if (features[10] <= 1351.50269f) {
            votes[1] += 1.0f;
            return;
          } else {
            votes[1] += 1.0f;
            return;
          }
        } else {
          votes[0] += 0.264485071f; votes[1] += 0.504556135f; votes[3] += 0.230958794f;
          return;
        }
      }
    }
  } else {
    if (features[2] <= 1.83974785f) {
      if (features[11] <= 1364.72998f) {
        if (features[9] <= 3.46150005f) {
          votes[2] += 0.883165829f; votes[4] += 0.116834171f;
          return;
        } else {
          if (features[11] <= 1355.48999f) {
            votes[2] += 0.986085395f; votes[4] += 0.0139146047f;
            return;
          } else {
            votes[2] += 1.0f;
            return;
          }
        }
      } else {
        if (features[2] <= 1.72664773f) {
          votes[4] += 1.0f;
          return;
        } else {
          votes[4] += 1.0f;
          return;
        }
      }
    } else {
      if (features[7] <= 6.48475003f) {
        votes[4] += 1.0f;
        return;
      } else {
        votes[2] += 0.739221872f; votes[4] += 0.260778128f;
        return;
      }
    }
  }
}

inline void motorV2Tree24(const float features[], float votes[]) {
  if (features[5] <= 2981.40259f) {
    if (features[1] <= 2785.58008f) {
      if (features[0] <= 10.8636847f) {
        if (features[0] <= 10.8286638f) {
          if (features[6] <= 2697.125f) {
            votes[4] += 1.0f;
            return;
          } else {
            votes[2] += 0.246083372f; votes[3] += 0.716536876f; votes[4] += 0.0373797526f;
            return;
          }
        } else {
          if (features[10] <= 1403.41693f) {
            votes[2] += 0.0320754717f; votes[3] += 0.967924528f;
            return;
          } else {
            votes[2] += 0.524097561f; votes[3] += 0.416195122f; votes[4] += 0.0597073171f;
            return;
          }
        }
      } else {
        if (features[6] <= 3570.39502f) {
          votes[1] += 1.0f;
          return;
        } else {
          votes[3] += 1.0f;
          return;
        }
      }
    } else {
      if (features[2] <= 1.69219768f) {
        if (features[10] <= 1454.98785f) {
          if (features[10] <= 1370.73688f) {
            votes[0] += 1.0f;
            return;
          } else {
            votes[0] += 1.0f;
            return;
          }
        } else {
          votes[4] += 1.0f;
          return;
        }
      } else {
        if (features[4] <= 1.43171042f) {
          if (features[0] <= 10.8670921f) {
            votes[0] += 0.554858934f; votes[1] += 0.445141066f;
            return;
          } else {
            votes[1] += 1.0f;
            return;
          }
        } else {
          votes[4] += 1.0f;
          return;
        }
      }
    }
  } else {
    if (features[7] <= 5.21994996f) {
      if (features[5] <= 3000.44995f) {
        if (features[10] <= 1368.20374f) {
          votes[2] += 1.0f;
          return;
        } else {
          votes[4] += 1.0f;
          return;
        }
      } else {
        votes[4] += 1.0f;
        return;
      }
    } else {
      if (features[8] <= 2.51850092f) {
        votes[3] += 0.912708601f; votes[4] += 0.0872913992f;
        return;
      } else {
        votes[4] += 1.0f;
        return;
      }
    }
  }
}

inline int motorV2Predict(const float features[MOTOR_V2_FEATURE_COUNT], float *confidence) {
  float votes[MOTOR_V2_CLASS_COUNT] = {0};
  motorV2Tree0(features, votes);
  motorV2Tree1(features, votes);
  motorV2Tree2(features, votes);
  motorV2Tree3(features, votes);
  motorV2Tree4(features, votes);
  motorV2Tree5(features, votes);
  motorV2Tree6(features, votes);
  motorV2Tree7(features, votes);
  motorV2Tree8(features, votes);
  motorV2Tree9(features, votes);
  motorV2Tree10(features, votes);
  motorV2Tree11(features, votes);
  motorV2Tree12(features, votes);
  motorV2Tree13(features, votes);
  motorV2Tree14(features, votes);
  motorV2Tree15(features, votes);
  motorV2Tree16(features, votes);
  motorV2Tree17(features, votes);
  motorV2Tree18(features, votes);
  motorV2Tree19(features, votes);
  motorV2Tree20(features, votes);
  motorV2Tree21(features, votes);
  motorV2Tree22(features, votes);
  motorV2Tree23(features, votes);
  motorV2Tree24(features, votes);
  int best = 0;
  for (int i = 1; i < MOTOR_V2_CLASS_COUNT; ++i) if (votes[i] > votes[best]) best = i;
  if (confidence != nullptr) *confidence = votes[best] / 25.0f;
  return best;
}
