; PlatformIO Project Configuration File for PDM Enhanced Embedded Node
; Board: ESP32-S3 DevKitC-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
    adafruit/Adafruit MPU6050@^2.2.9
    adafruit/Adafruit NeoPixel@^1.12.0
monitor_speed = 115200
build_flags =
    -O3
    -ffast-math
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384

 