"""Train a small decision tree and export it as ESP32 C++ source.

This uses only eight time-domain/RPM features so the ESP32 can classify a
one-second (200 sample) window without Python, a filesystem, or an FFT.
Run from the project root after changing the ML dataset:

    python log_file/scripts/train_embedded_model.py
"""

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.tree import DecisionTreeClassifier


DATASET = Path("log_file/output290826/ml_dataset.csv")
HEADER = Path("include/motor_model.h")

# These are the eight most useful features from the reference Random Forest,
# excluding FFT features so the classifier can run on the ESP32 in real time.
FEATURES = [
    "az_mean", "rpm_min", "ay_rms", "ay_std", "ax_crest",
    "rpm_median", "rpm_max", "ay_p2p",
]

MAX_DEPTH = 6
MIN_SAMPLES_LEAF = 5


def validate(df: pd.DataFrame) -> None:
    x, y, groups = df[FEATURES], df["fault_id"], df["group"]
    cv = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
    actual, predicted = [], []
    for train, test in cv.split(x, y, groups):
        classifier = DecisionTreeClassifier(
            max_depth=MAX_DEPTH,
            min_samples_leaf=MIN_SAMPLES_LEAF,
            class_weight="balanced",
            random_state=42,
        ).fit(x.iloc[train], y.iloc[train])
        actual.extend(y.iloc[test])
        predicted.extend(classifier.predict(x.iloc[test]))

    print("Embedded decision-tree grouped CV")
    print(f"  Accuracy:          {accuracy_score(actual, predicted) * 100:.2f}%")
    print(f"  Balanced accuracy: {balanced_accuracy_score(actual, predicted) * 100:.2f}%")
    print(f"  Macro F1:          {f1_score(actual, predicted, average='macro'):.3f}")


def emit_node(tree, node: int, indent: str) -> list[str]:
    left, right = tree.children_left[node], tree.children_right[node]
    if left == right:
        return [f"{indent}return {int(np.argmax(tree.value[node][0]))};"]
    feature = int(tree.feature[node])
    threshold = float(tree.threshold[node])
    output = [f"{indent}if (features[{feature}] <= {threshold:.9g}f) {{"]
    output.extend(emit_node(tree, left, indent + "  "))
    output.append(f"{indent}}} else {{")
    output.extend(emit_node(tree, right, indent + "  "))
    output.append(f"{indent}}}")
    return output


def export_header(model: DecisionTreeClassifier) -> None:
    labels = [str(label) for label in model.classes_]
    label_lines = ", ".join(f'"{label}"' for label in labels)
    feature_lines = ", ".join(f'"{feature}"' for feature in FEATURES)
    body = "\n".join(emit_node(model.tree_, 0, "  "))
    text = f"""// Generated by log_file/scripts/train_embedded_model.py. Do not edit manually.
#pragma once

constexpr int MOTOR_FEATURE_COUNT = {len(FEATURES)};
static const char *const MOTOR_FEATURE_NAMES[MOTOR_FEATURE_COUNT] = {{{feature_lines}}};
static const char *const MOTOR_LABELS[] = {{{label_lines}}};

// Feature order: az_mean, rpm_min, ay_rms, ay_std, ax_crest, rpm_median, rpm_max, ay_p2p.
// Return value is the index into MOTOR_LABELS.
inline int motorPredict(const float features[MOTOR_FEATURE_COUNT]) {{
{body}
}}
"""
    HEADER.write_text(text)
    print(f"Exported: {HEADER}")
    print(f"Tree depth: {model.get_depth()}, leaves: {model.get_n_leaves()}")
    print("Class index mapping:", dict(enumerate(labels)))


def main() -> None:
    df = pd.read_csv(DATASET)
    missing = [feature for feature in FEATURES if feature not in df.columns]
    if missing:
        raise ValueError(f"Dataset is missing: {missing}")
    if not np.isfinite(df[FEATURES].to_numpy(dtype=float)).all():
        raise ValueError("Dataset contains invalid values in embedded-model features.")
    validate(df)
    model = DecisionTreeClassifier(
        max_depth=MAX_DEPTH,
        min_samples_leaf=MIN_SAMPLES_LEAF,
        class_weight="balanced",
        random_state=42,
    ).fit(df[FEATURES], df["fault_id"])
    export_header(model)


if __name__ == "__main__":
    main()
