"""Export trained Random Forest model to high-performance standalone C++ header.

Generates pdm_model.h containing pure C/C++ decision tree evaluation with:
- Zero external ML dependencies
- Direct float array evaluation
- Instantaneous Health Index and confidence calculations
"""

from __future__ import annotations
from pathlib import Path
import joblib
import numpy as np

ROOT_DIR = Path(__file__).resolve().parent.parent
MODEL_PATH = ROOT_DIR / "models" / "saved_models" / "pdm_fault_model.pkl"
HEADER_PATH = ROOT_DIR / "embedded" / "include" / "pdm_model.h"


def format_c_float(val: float) -> str:
    """Format float as C++ single precision literal."""
    text = f"{float(val):.9g}"
    if "." not in text and "e" not in text.lower():
        text += ".0"
    return text + "f"


def emit_tree_nodes(tree, node_id: int, indent: str, tree_idx: int) -> list[str]:
    """Recursively emit branching C++ if/else code for a decision tree node."""
    left = tree.children_left[node_id]
    right = tree.children_right[node_id]

    if left == right:  # Leaf node
        values = tree.value[node_id][0]
        total = float(np.sum(values))
        if total <= 0:
            return [f"{indent}return;"]
        adds = " ".join(
            f"votes[{c_idx}] += {format_c_float(val / total)};"
            for c_idx, val in enumerate(values)
            if val > 0
        )
        return [f"{indent}{adds}", f"{indent}return;"]

    feat_idx = int(tree.feature[node_id])
    thresh = float(tree.threshold[node_id])
    lines = [f"{indent}if (features[{feat_idx}] <= {format_c_float(thresh)}) {{"]
    lines.extend(emit_tree_nodes(tree, left, indent + "  ", tree_idx))
    lines.append(f"{indent}}} else {{")
    lines.extend(emit_tree_nodes(tree, right, indent + "  ", tree_idx))
    lines.append(f"{indent}}}")
    return lines


def generate_header() -> Path:
    """Load trained model and generate C++ header."""
    HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not MODEL_PATH.exists():
        raise FileNotFoundError(f"Model artifact not found: {MODEL_PATH}")

    artifact = joblib.load(MODEL_PATH)
    model = artifact["model"]
    features = artifact["features"]
    classes = list(model.classes_)
    num_trees = len(model.estimators_)

    healthy_idx = classes.index("HEALTHY") if "HEALTHY" in classes else 0

    tree_functions = []
    tree_calls = []

    for tree_idx, estimator in enumerate(model.estimators_):
        func_name = f"pdmTree{tree_idx}"
        lines = [f"inline void {func_name}(const float features[], float votes[]) {{"]
        lines.extend(emit_tree_nodes(estimator.tree_, 0, "  ", tree_idx))
        lines.append("}\n")
        tree_functions.append("\n".join(lines))
        tree_calls.append(f"  {func_name}(features, votes);")

    feat_names_str = ", ".join(f'"{name}"' for name in features)
    label_names_str = ", ".join(f'"{name}"' for name in classes)

    c_code = f"""// ============================================================================
// Enhanced Predictive Maintenance: Generated Embedded Model
// Automatically generated by export_c_header.py — DO NOT EDIT DIRECTLY.
// ============================================================================

#pragma once

#ifndef PDM_MODEL_H
#define PDM_MODEL_H

#include <math.h>

constexpr int PDM_FEATURE_COUNT = {len(features)};
constexpr int PDM_CLASS_COUNT = {len(classes)};
constexpr int PDM_NUM_TREES = {num_trees};
constexpr int PDM_HEALTHY_CLASS_INDEX = {healthy_idx};

static const char *const PDM_FEATURE_NAMES[PDM_FEATURE_COUNT] = {{
    {feat_names_str}
}};

static const char *const PDM_LABELS[PDM_CLASS_COUNT] = {{
    {label_names_str}
}};

// Individual Tree Estimators
{chr(10).join(tree_functions)}

/**
 * Predict motor fault condition and compute real-time metrics.
 * 
 * @param features      Array of PDM_FEATURE_COUNT input features
 * @param confidence    Output pointer for model confidence (0.0 to 1.0)
 * @param health_index  Output pointer for continuous Health Index (0.0 to 100.0)
 * @return              Predicted class index (0 to PDM_CLASS_COUNT - 1)
 */
inline int pdmPredict(
    const float features[PDM_FEATURE_COUNT],
    float *confidence = nullptr,
    float *health_index = nullptr
) {{
  float votes[PDM_CLASS_COUNT] = {{0.0f}};

{chr(10).join(tree_calls)}

  // Find argmax class
  int best_class = 0;
  float max_vote = votes[0];
  for (int i = 1; i < PDM_CLASS_COUNT; ++i) {{
    if (votes[i] > max_vote) {{
      max_vote = votes[i];
      best_class = i;
    }}
  }}

  if (confidence != nullptr) {{
    *confidence = max_vote / (float)PDM_NUM_TREES;
  }}

  if (health_index != nullptr) {{
    *health_index = (votes[PDM_HEALTHY_CLASS_INDEX] / (float)PDM_NUM_TREES) * 100.0f;
  }}

  return best_class;
}}

#endif // PDM_MODEL_H
"""

    HEADER_PATH.write_text(c_code)
    print(f"Generated C++ Header: {HEADER_PATH}")
    print(f"Features: {len(features)}, Trees: {num_trees}, Classes: {len(classes)}")
    return HEADER_PATH


if __name__ == "__main__":
    generate_header()
